//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoGameStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Employee_Address = new HashSet<Employee_Address>();
            this.Store_Event_Employee = new HashSet<Store_Event_Employee>();
        }
    
        public int employee_id { get; set; }
        public string username { get; set; }
        public string employee_password { get; set; }
        public int login_failures { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public System.DateTime birthdate { get; set; }
        public System.DateTime date_hired { get; set; }
        public bool is_admin { get; set; }
        public bool is_inactive { get; set; }
        public bool is_locked_out { get; set; }
        public string notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Address> Employee_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Store_Event_Employee> Store_Event_Employee { get; set; }
    }
}
