//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoGameStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend_List
    {
        public int user_id { get; set; }
        public int friend_id { get; set; }
        public bool is_family { get; set; }
        public System.DateTime date_added { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
