//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoGameStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int review_id { get; set; }
        public int user_id { get; set; }
        public int game_id { get; set; }
        public System.DateTime review_date { get; set; }
        public string review_content { get; set; }
        public bool is_approved { get; set; }
        public bool is_deleted { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual User User { get; set; }
    }
}
