//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoGameStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Report
    {
        public string game_name { get; set; }
        public Nullable<decimal> Units_Sold { get; set; }
        public Nullable<decimal> Profit_Margin { get; set; }
        public Nullable<decimal> Sales_Volume { get; set; }
        public Nullable<decimal> Total_Profit { get; set; }
    }
}
