//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoGameStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_Event_Customer
    {
        public int store_event_customer_id { get; set; }
        public int store_event_id { get; set; }
        public int customer_id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Store_Event Store_Event { get; set; }
    }
}
