//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoGameStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VideoGameStoreDBContext : DbContext
    {
        public VideoGameStoreDBContext()
            : base("name=VideoGameStoreDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Credit_Card> Credit_Card { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Customer_Address> Customer_Address { get; set; }
        public virtual DbSet<Customer_Game> Customer_Game { get; set; }
        public virtual DbSet<Developer> Developers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee_Address> Employee_Address { get; set; }
        public virtual DbSet<Friend_List> Friend_List { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Invoice_Address> Invoice_Address { get; set; }
        public virtual DbSet<Line_Item> Line_Item { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Publisher> Publishers { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Store_Event> Store_Event { get; set; }
        public virtual DbSet<Store_Event_Customer> Store_Event_Customer { get; set; }
        public virtual DbSet<Store_Event_Employee> Store_Event_Employee { get; set; }
        public virtual DbSet<Wish_List> Wish_List { get; set; }
        public virtual DbSet<Sales_Report> Sales_Report { get; set; }
    }
}
