//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoGameStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Address
    {
        public int invoice_address_id { get; set; }
        public int invoice_id { get; set; }
        public int address_id { get; set; }
        public bool is_billing_address { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
